### ISSUE TITLE
404 Not Found issue, and it's fix

### ISSUE THREAD

**Issue by kennypu** [halgatewood/youtube-thumbnail-enhancer#2]
So I found that the script will always give 404 Not Found. To fix, change the curl_init target on line 65 to SSL:

$handle = curl_init("http://www.youtube.com/watch/?v=" . $id);
to
$handle = curl_init("https://www.youtube.com/watch/?v=" . $id);

**Comment by halgatewood** [comment]
Good catch, I'll update the script. Thanks!

**Comment by kennypu** [comment]
no problem!
